from setuptools import setup
import os

setup(
    name='merlinth',
    version='0.3.1',
    author="Kerstin Hammernik, Thomas Kuestner",
    author_email="k.hammernik@imperial.ac.uk, thomas.kuestner@med.uni-tuebingen.de",
    packages=["merlinth",
              "merlinth.optim",
              "merlinth.layers",
              "merlinth.losses",
              "merlinth.layers.convolutional",
              "merlinth.models",
              "merlinth.test",
              ],
    package_dir={"merlinth": os.path.join('.', "merlinth"),
                 "merlinth.optim": os.path.join('.', "merlinth/optim"),
                 "merlinth.layers": os.path.join('.', "merlinth/layers"),
                 "merlinth.losses": os.path.join('.', "merlinth/losses"),
                 "merlinth.layers.convolutional": os.path.join('.', "merlinth/layers/convolutional"),
                 "merlinth.models": os.path.join('.', "merlinth/models"),
                 "merlinth.test": os.path.join('.', "merlinth/test"),
    },
    install_requires=[
        "numpy >= 1.15",
        "torch >= 1.0.0",
        "torchvision >= 0.2.1",
    ],
    license='MIT',
    url='https://github.com/midas-tum/merlin',
    description='Machine Enhanced Reconstruction Learning and Interpretation Networks (MERLIN) - merlinth',
    long_description=open('../README.md').read(),
    long_description_content_type='text/markdown',
    classifiers=[
        "Programming Language :: Python :: 3 :: Only",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
    ],
)