name: merlin-test
on: [push]
jobs:
  run:
    runs-on: [self-hosted,Linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Activate environment
        shell: bash -l {0}
        run: |
          # activate pre-configured environment with installed optox
          ~/miniconda3/condabin/conda init
          source ~/.bashrc
          ~/miniconda3/condabin/conda activate actions-merlin
      - name: Build merlin 
        shell: bash -l {0}
        run: |
          cd ~/actions-runner-merlin/_work/merlin/merlin
          ./install.sh
      - name: Check install
        shell: bash -l {0}
        run: |
          conda info
          conda list
          pip list
      - name: Run python unittests
        shell: bash -l {0}
        run: |
          python3 -m unittest discover -s merlinpy -p "*.py" >> results_py.txt
      - name: Run pytorch unittests
        shell: bash -l {0}
        run: |
          python3 -m unittest discover -s merlinth -p "*.py" >> results_th.txt
      - name: Run tensorflow unittests
        shell: bash -l {0}
        run: |
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/lib64
          python3 -m unittest discover -s merlintf -p "*.py" >> results_tf.txt
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat results_py.txt results_tf.txt results_th.txt >> report.md
          cml-send-comment report.md